# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # admin_name: First User
  # admin_email: user@example.com
  # admin_password: changeme
  admin_name: Kapranov
  admin_email: lugatex@yahoo.com
  admin_password: aipsiraf6922
  domain_name: example.com
  secret_key_base: 28067abf5534f016d350b8bbedb103a1f4e61e090b635a38690a7f9aa96e8573eadd318a8e7b3bf5829d1c4d18a053155634bced51001659e37a49fe06f509e9

test:
  domain_name: example.com 
  secret_key_base: 7aa075dc83890fcc257b06876654ad692d62e75713ae63e780830b950f0e98f11c47c67122b74c354461239f3a4b957561875e3372294f08bd98400702a1a5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
